### ISSUE TITLE
test_rpmdb_centos7_missing_index fails when building dcrpm with setuptools 60.9.3 in Fedora

### ISSUE THREAD

**Issue by befeleme** [facebookincubator/dcrpm#47]
Hello,
I'm working on integrating setuptools 60+ to Fedora and test it against all packages in Fedora Rawhide (the rebuild takes place in [Copr repository](https://copr.fedorainfracloud.org/coprs/ksurma/setuptools-60/package/python-dcrpm/). One of the big-impact changes is the new default: setuptools uses its own distutils (rather than the one from Python's standard library).
One of dcrpm's tests fails every time with the newest setuptools and builds successfully every time with setuptools 59.6.0 we already have in Fedora. The test failure is rather weird though, there's no clear (to me) connection to setuptools that could play any role here.  Do you have any idea why does this happen?

```console
FAIL: test_rpmdb_centos7_missing_index (tests.test_end_to_end.DcrpmIntegrationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dcrpm-0.6.2/tests/rpmdb.py", line 38, in wrapper
    result = t.cast(F, function)(*args, **kwargs)
  File "/builddir/build/BUILD/dcrpm-0.6.2/tests/test_end_to_end.py", line 92, in test_rpmdb_centos7_missing_index
    self.assertEqual(self.action_trace(), [])
AssertionError: Lists differ: ['index_rebuild', 'index_rebuild', 'table_rebuild'] != []

First list contains 3 additional elements.
First extra element 0:
'index_rebuild'

- ['index_rebuild', 'index_rebuild', 'table_rebuild']
+ []

----------------------------------------------------------------------
Ran 67 tests in 7.490s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=67 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=67 errors=0 failures=1>
```

**Comment by michel-slm** [comment]
@befeleme could you file this in Bugzilla too? (I comaintain `python-dcrpm` there).

It's a weird error indeed - I'll take a look

**Comment by michel-slm** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=2071821 to track since it still reproduces (`fedpkg scratch-build` after `fedpkg clone python-dcrm`)
