### ISSUE TITLE
Acquire db_stat details about the rpmdb before running db_recover

### ISSUE THREAD

**Issue by n3npq** [facebookincubator/dcrpm#6]
dcrpm runs rpm -qa as a heuristic to determine whether an rpmdb is accessible, followed by running db_recover on a timeout (or other) failure. Unfortunately db_recover destroys whatever state that can be used to diagnose the root cause.

Capturing "db_stat -CA" (or at least "db_stat -Cl") would help classify "stale lock" deadlock problems from timeouts.

Checking for the DB_ RUNRECOVERY error message on steer would help classify dbenv recovery problems. You might also consider writing a simple program to open&eclipse the rpmdb dbenv instead of reading the 100Mb of content in Packages (rpm -qa is perhaps not the best heuristic, although there really isn't a better means to get a package count than rpm -qa line count)

Finally, db_recovery can be run with a "-evv" to preserve the dbenv files: there are known (but rare) problems if/when there are multiple instances of dbenv files attached to different processes which can happen if open files are unlinked. Preserving the dbenv files with db_recover is recommended to avoid.

**Comment by jaymzh** [comment]
For the first point - you're proposing running `db_stat -CA` and capturing that before the recover so we can then provide that in a bug report? Or am I misunderstanding? Gathering useful data seems sane to me.

For the second one, ... I'm guessing s/steer/stderr/ ? are you saying having dcrpm try to open the env and check for stderr? I'm not following your second comment.

For the third one... you're saying we should preserve the dbenv files, but then saying it's recommended to avoid doing that? I'm confused.

**Comment by n3npq** [comment]
Overall I am recommending classifying your dcrpm failure modes in order to actually diagnose the problems.

Re 1): yes, useful data. Using db_stat -CA is complete including pids/tides, but db_stat -Cl is what is most useful for detecting database deadlocks (and stale locks if pid/tid isn't currently running).

Re 2): yes stderr. Berkeley DB helpfully spews on stderr with DB_ RUNRECOVERY when db_recover is needed. Ideally that should be the *only* time that db_recover is invoked (but db_recover also removes deadlocks/stalelocks as side effect, but there are better alternative fixes for those problems). A stub program to simply open/close an rpmdb dbenv is sufficient to return DB_RUNRECOVER and is far less overhead than than the rpm -qa heuristic reading ~100Mb.

Re 3): yes, run db_recover -e and *always* preserve the dbenv files. The reason to preserve is that db_recover is designed to handle file open races in the dbenv, and there are race windows both through reopening a dbenv, and in deleting a dbenv  in how rpm handles a dbenv. You don't want the additional overhead of dcrpm causing Yet More "corruption" than is already (allegedly) present.

**Comment by n3npq** [comment]
FWIW, dcrpm should also note (and perhaps honor) the exclusive write fcntl lock that is intended to serialize rpm operations. Specifically, log if/when the lock is help by some other pid when dcrpm is run, and perhaps wait a bit for the other pid to complete before blasting away with signals.

The reason is that only exclusive writers are well tested using the fcntl lock, shared readers (like rpm -qa) are less well tested.

Note also that relying on cooperative signal handling between yum <-> rpmlib is (and always has been) contentious. rpmlib tries to use atexit(3) to gracefully close an rpmdb. If an rpmdb is *NOT* closed on exit, then you *WILL* have rpmdb problems.

**Comment by davide125** [comment]
Looks like the bulk of this was addressed back in 2018, closing.
